version: "3.3"


services:
  www:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
      - "3030:443"
    links:
      - db
    networks:
      - default 


  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - default
    volumes:
      - ./app/config/setup.sql:/docker-entrypoint-initdb.d/init.sql



  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 3001:80
    environment:
      MYSQL_ROOT_PASSWORD: root



volumes:
  persistent: